### PR TITLE
Adding a rendered (GitHub) dashboard of existing listed providers and sub-dbs

### PR DESCRIPTION
**Pull request by giovannipizzi**
This also does a minimal validation, and shows some information if there is e.g. a validation error.

You can see the currently rendered version here: https://giovannipizzi.github.io/providers/
(The final URL will be different, it will be on the Github Pages of this repo and not of my fork)

### CODE REVIEW

**Comment by rartino** [comment]
This is really cool, but is the providers repository the right place for it? I think this seems so much more tied to the central OPTIMADE webpage. And I am a bit worried about adding complexity to the providers repository. 

It would either have to be implemented dynamically (javascript pulling the providers.json and rendering it) or we would have to 'ping' an update of the optimade webpage upon committing to the main branch of providers.

**Comment by giovannipizzi** [comment]
@rartino For this specific use case (just rendering what is here), I think tying to this repo is not necessarily bad. But if we prefer to do it elsewhere, I can create a custom repo (I wouldn't do in the same as the main webpage, also because I'd like Github Pages and I don't want to mess up with the main web page, I have to force push and replace that branch.

@fekad indeed I like the idea, we'll probably need some time to implement it. Any help is welcome there! Maybe one could create some scaffolding and then make it easy for people to add more tests (rows). This, however, would definitely be part of a different repo.

@rartino indeed a JS client might be better, but I'm much less experienced and it would have taken me much longer (besides, I could use the `optimade-python-tools` here for validation.

Also, as a note: this is a scheduled run, running once per day.
I think it's acceptable, for the speed at which we change things or add new entries, to wait a few hours for updates to be visible (and I indicate the last update). I can also make it a bit more often (every hour?).
And, if needed, it's just a click in the GitHub interface to re-run it on demand. So it's probably acceptable.

Let me know if you prefer that I just create a new repo for this (and then this would be also hosting the tests like those suggested today, and eventually those suggested by @fekad . And a suggestion for the name for the repo (e.g. `known-implementations`?)

**Comment by rartino** [comment]
If this is scheduled, rather than run on merge, I definitely think it should go in a different repository to not add unnecessary complexity to the present repository. I can give more reasons if you want to, but in particular I see use-cases of wanting to clone this repository to get access to (the various versions of) the providers lists, and it would be nice to be able to do so without having to pull in a large chunks of web code.

I don't get your argument against adding this to the main webpage repo. Why would you have to force-push? Can't you just add this github workflow to that repo?

**Comment by blokhin** [comment]
Agreed with @rartino, a separate repo called something like `providers-dashboard` makes sense.

**Comment by giovannipizzi** [comment]
Ok, I'll create a new repo. @rartino, just to answer your question: this GitHub Actions, at the end, force-pushes to the gh-pages branch all the static html files that have been created. I fear this will conflict with the way the current webpage works. But I don't think it's a problem if we do it in a different repository - we just need to put then a link to the correct URL, and we can keep the logic independent of the "static" website

**Comment by giovannipizzi** [comment]
Closing this - I moved it to 
https://github.com/Materials-Consortia/providers-dashboard
with a compiled dashboard here:
http://www.optimade.org/providers-dashboard/

Feel free to work and comment there for further discussions.

Note that a number of providers still don't show sub-dbs because they are not using yet the new `link_type="child"` attribute in their links

**Pull request closed without merging**
